# A good soldier need a good terminal. (i think...)
font_family      Maple Mono Bold
font_size        10

background       #dbd5d1
foreground       #2d2926

cursor           #2d2926
selection_background #3a3a3a
selection_foreground #ffffff

window_padding_width 10

# Transparency, because... Why not?
background_opacity 0.95

# Scrolling.
scrollback_lines 10000

# Tab bar colors.
active_tab_foreground   #dbd5d1
active_tab_background   #2d2926
inactive_tab_foreground #2d2926
inactive_tab_background #9a938d

# The 16 terminal colors.

# Black
color0 #2d2926
color8 #5c554f

# Red
color1 #8c3b3b
color9 #a64b4b

# Green
color2 #5e695e
color10 #788578

# Yellow (Accent Gray)
color3 #9a938d
color11 #b8afa7

# Blue
color4 #4e5a6b
color12 #67758a

# Magenta
color5 #7d5c7d
color13 #9c739c

# Cyan
color6 #5c7d7d
color14 #739c9c

# White
color7 #9a938d
color15 #dbd5d1


# BEGIN_KITTY_FONTS
font_family      family='Maple Mono' style=Bold
bold_font        family='Maple Mono' postscript_name=MapleMono-Bold
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
